### PR TITLE
Mod til:

### PR DESCRIPTION
**Pull request by n2i**
- Avoid unnescessary addition newline when echo -e: using \c
- The new MDFILE will contain exactly 7 lines
- If the editor is vim, put the cursor at the beginning of 6th line, which is where
  the user may begin input their text
- The 7th line is the EOF

### CODE REVIEW

**Comment by khanhicetea** [comment]
The idea jumping cursor is good 👍 

Btw, you can use `wc -l` to count lines and jump to exactly line number. Could you add it in this PR ?

**Comment by n2i** [comment]
Got it! I will do, in following commit(s).

**Comment by khanhicetea** [comment]
Wow, nice work ! 👍 

Btw, I don't think full filename including date is good, because we already have date in file content. I want separate to subject only so readers (not author) can easier to navigate 😄 Let me know your thought

**Comment by n2i** [comment]
I'm sorry for a really long delay on replying. I have not been online for a week.

CREATEDDATE: I agree with you, and removed this part in the MDFILE. Just do KISS (principle).

**Comment by khanhicetea** [comment]
I merged this PR, thank you for your great work 👍

**Pull request merged**
